/**
*    Copyright (C) 2008 10gen Inc.
*  
*    This program is free software: you can redistribute it and/or  modify
*    it under the terms of the GNU Affero General Public License, version 3,
*    as published by the Free Software Foundation.
*  
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*  
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated By:JJTree: Do not edit this line. MQLINTEGERLITERAL.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;

public class MQLINTEGERLITERAL extends SimpleNode {
    public MQLINTEGERLITERAL(int id) {
        super(id);
    }

    public MQLINTEGERLITERAL(MQL p, int id) {
        super(p, id);
    }

    public String stringJSForm() {

        String s = "";
        if (children != null && children.length == 0) {
            s = ((SimpleNode) children[0]).stringJSForm();
        }
        return s + this.token.image;
    }
}
/* JavaCC - OriginalChecksum=2816f058e45e3e0261b65c3bf195f9e3 (do not edit this line) */
