/**
*      Copyright (C) 2008 10gen Inc.
*  
*    Licensed under the Apache License, Version 2.0 (the "License");
*    you may not use this file except in compliance with the License.
*    You may obtain a copy of the License at
*  
*       http://www.apache.org/licenses/LICENSE-2.0
*  
*    Unless required by applicable law or agreed to in writing, software
*    distributed under the License is distributed on an "AS IS" BASIS,
*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*    See the License for the specific language governing permissions and
*    limitations under the License.
*/

/* Generated By:JJTree: Do not edit this line. MQLIDENTIFICATIONVARIABLE.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;
import ed.db.mql.Token;

public class MQLIDENTIFICATIONVARIABLE extends SimpleNode {
  public MQLIDENTIFICATIONVARIABLE(int id) {
    super(id);
  }

  public MQLIDENTIFICATIONVARIABLE(MQL p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=0e674f865846fb4e3936330cacf3106f (do not edit this line) */
