/**
*    Copyright (C) 2008 10gen Inc.
*  
*    This program is free software: you can redistribute it and/or  modify
*    it under the terms of the GNU Affero General Public License, version 3,
*    as published by the Free Software Foundation.
*  
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*  
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated By:JJTree: Do not edit this line. MQLLIMIT.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;
import ed.db.mql.QueryInfo;

public class MQLLIMIT extends SimpleNode {
    public MQLLIMIT(int id) {
        super(id);
    }

    public MQLLIMIT(MQL p, int id) {
        super(p, id);
    }

    public void render(QueryInfo qi) {
        updateQI(qi);
    }

    public void updateQI(QueryInfo qi) {

        qi.setLimit(Integer.valueOf(((SimpleNode) children[0]).getFirstToken().image));
    }

}
/* JavaCC - OriginalChecksum=1fd5112f34f2d135ef8c121521a1ca60 (do not edit this line) */
