/**
*      Copyright (C) 2008 10gen Inc.
*  
*    Licensed under the Apache License, Version 2.0 (the "License");
*    you may not use this file except in compliance with the License.
*    You may obtain a copy of the License at
*  
*       http://www.apache.org/licenses/LICENSE-2.0
*  
*    Unless required by applicable law or agreed to in writing, software
*    distributed under the License is distributed on an "AS IS" BASIS,
*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*    See the License for the specific language governing permissions and
*    limitations under the License.
*/

/* Generated By:JJTree: Do not edit this line. MQLMOD.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;

public class MQLMOD extends SimpleNode {
    public MQLMOD(int id) {
        super(id);
    }

    public MQLMOD(MQL p, int id) {
        super(p, id);
    }

    public String stringJSForm() {
        return " % ";
    }
}
/* JavaCC - OriginalChecksum=4e9e5bf20408744687feebc050eb281c (do not edit this line) */
