/**
*    Copyright (C) 2008 10gen Inc.
*  
*    This program is free software: you can redistribute it and/or  modify
*    it under the terms of the GNU Affero General Public License, version 3,
*    as published by the Free Software Foundation.
*  
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*  
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated By:JJTree: Do not edit this line. MQLORDERBY.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;
import ed.db.mql.QueryInfo;
import ed.db.mql.Node;
import ed.db.mql.MQLTreeConstants;

public class MQLORDERBY extends SimpleNode {
    public MQLORDERBY(int id) {
        super(id);
    }

    public MQLORDERBY(MQL p, int id) {
        super(p, id);
    }

    public void render(QueryInfo qi) {

        for (Node n : children) {

            SimpleNode sn = (SimpleNode) n;

            assert (sn.getId() == MQLTreeConstants.JJTORDERBYITEM);

            String what = ((SimpleNode) sn.jjtGetChild(0)).stringJSForm();
            int id = ((SimpleNode) sn.jjtGetChild(1)).getId();
            qi.addOrderBy(new QueryInfo.Field(what, id == MQLTreeConstants.JJTASCENDING ? "1" : "-1"));
        }
    }
}
/* JavaCC - OriginalChecksum=637cca873460b9bf0c6ad8d924bcf86b (do not edit this line) */
