/**
*    Copyright (C) 2008 10gen Inc.
*  
*    This program is free software: you can redistribute it and/or  modify
*    it under the terms of the GNU Affero General Public License, version 3,
*    as published by the Free Software Foundation.
*  
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*  
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated By:JJTree: Do not edit this line. MQLSTRINGLITERAL.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;

public class MQLSTRINGLITERAL extends SimpleNode {
    public MQLSTRINGLITERAL(int id) {
        super(id);
    }

    public MQLSTRINGLITERAL(MQL p, int id) {
        super(p, id);
    }

    public String stringJSForm() {

        String s = getFirstToken().image;

        if (s != null) {
            int start = 0;
            int end = s.length();

            if (s.startsWith("'") || s.startsWith("\"")) {
                start++;
            }
            if (s.endsWith("'") || s.endsWith("\"")) {
                end--;
            }

            s = s.substring(start, end);
        }

        return "\"" + s + "\"";
    }

}
/* JavaCC - OriginalChecksum=4d69a54db1b8bfe5f44eefd917305bb9 (do not edit this line) */
