/**
*    Copyright (C) 2008 10gen Inc.
*  
*    This program is free software: you can redistribute it and/or  modify
*    it under the terms of the GNU Affero General Public License, version 3,
*    as published by the Free Software Foundation.
*  
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*  
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated By:JJTree: Do not edit this line. MQLSELECTEXPRESSION.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;
import ed.db.mql.QueryInfo;
import ed.db.mql.MQLTreeConstants;

public class MQLSELECTEXPRESSION extends SimpleNode {
    public MQLSELECTEXPRESSION(int id) {
        super(id);
    }

    public MQLSELECTEXPRESSION(MQL p, int id) {
        super(p, id);
    }

    public void render(QueryInfo qi) {

        SimpleNode sn = (SimpleNode) children[0];

        if (sn.getId() == MQLTreeConstants.JJTAGGREGATE) {
            // a count(*) so just do the right thing...

            SimpleNode agg = (SimpleNode) sn.jjtGetChild(0);
            agg.updateQI(qi);
        } else {
            // assume a field selection expression

            qi.addReturnField(new QueryInfo.Field(sn.stringJSForm()));
        }
    }
}
/* JavaCC - OriginalChecksum=6df2c59ee984913560de61cab3f8ee76 (do not edit this line) */
