/**
*      Copyright (C) 2008 10gen Inc.
*  
*    Licensed under the Apache License, Version 2.0 (the "License");
*    you may not use this file except in compliance with the License.
*    You may obtain a copy of the License at
*  
*       http://www.apache.org/licenses/LICENSE-2.0
*  
*    Unless required by applicable law or agreed to in writing, software
*    distributed under the License is distributed on an "AS IS" BASIS,
*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*    See the License for the specific language governing permissions and
*    limitations under the License.
*/

/* Generated By:JJTree: Do not edit this line. MQLSELECTEXPRESSION.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;
import ed.db.mql.QueryInfo;
import ed.db.mql.MQLTreeConstants;

public class MQLSELECTEXPRESSION extends SimpleNode {
    public MQLSELECTEXPRESSION(int id) {
        super(id);
    }

    public MQLSELECTEXPRESSION(MQL p, int id) {
        super(p, id);
    }

    public void render(QueryInfo qi) {

        SimpleNode sn = (SimpleNode) children[0];

        if (sn.getId() == MQLTreeConstants.JJTAGGREGATE) {
            // a count(*) so just do the right thing...

            SimpleNode agg = (SimpleNode) sn.jjtGetChild(0);
            agg.updateQI(qi);
        } else {
            // assume a field selection expression

            qi.addReturnField(new QueryInfo.Field(sn.stringJSForm(), MQLTreeConstants.JJTPATH));
        }
    }
}
/* JavaCC - OriginalChecksum=6df2c59ee984913560de61cab3f8ee76 (do not edit this line) */
