/**
*    Copyright (C) 2008 10gen Inc.
*  
*    This program is free software: you can redistribute it and/or  modify
*    it under the terms of the GNU Affero General Public License, version 3,
*    as published by the Free Software Foundation.
*  
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*  
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated By:JJTree: Do not edit this line. MQLSUBTRACT.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;

public class MQLSUBTRACT extends SimpleNode {
  public MQLSUBTRACT(int id) {
    super(id);
  }

  public MQLSUBTRACT(MQL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed4ab12745709657e8c062746103c8f6 (do not edit this line) */
