/**
*    Copyright (C) 2008 10gen Inc.
*  
*    This program is free software: you can redistribute it and/or  modify
*    it under the terms of the GNU Affero General Public License, version 3,
*    as published by the Free Software Foundation.
*  
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*  
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated By:JJTree: Do not edit this line. MQLUPDATEITEM.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;
import ed.db.mql.QueryInfo;

public class MQLUPDATEITEM extends SimpleNode {
  public MQLUPDATEITEM(int id) {
    super(id);
  }

  public MQLUPDATEITEM(MQL p, int id) {
    super(p, id);
  }

    public void render(QueryInfo qi) {

        updateQI(qi);
    }

    public void updateQI(QueryInfo qi) {

        SimpleNode leftNode = (SimpleNode) children[0];
        SimpleNode rightNode = (SimpleNode) children[2];

        int rightId = ((SimpleNode) children[2].jjtGetChild(0)).getId();

        qi.addSetField(new QueryInfo.Field(leftNode.stringJSForm(), leftNode.getId(),
                                            rightNode.stringJSForm(), rightId));
    }
}
/* JavaCC - OriginalChecksum=b4cc3a7edd04e3ea35c5f9c12eb936af (do not edit this line) */
