/**
*    Copyright (C) 2008 10gen Inc.
*  
*    This program is free software: you can redistribute it and/or  modify
*    it under the terms of the GNU Affero General Public License, version 3,
*    as published by the Free Software Foundation.
*  
*    This program is distributed in the hope that it will be useful,
*    but WITHOUT ANY WARRANTY; without even the implied warranty of
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*    GNU Affero General Public License for more details.
*  
*    You should have received a copy of the GNU Affero General Public License
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated By:JJTree: Do not edit this line. MQLWHERE.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=MQL,NODE_EXTENDS=,NODE_FACTORY= */
package ed.db.mql.nodes;

import ed.db.mql.SimpleNode;
import ed.db.mql.MQL;
import ed.db.mql.QueryInfo;
import ed.db.mql.MQLTreeConstants;

public class MQLWHERE extends SimpleNode {
    public MQLWHERE(int id) {
        super(id);
    }

    public MQLWHERE(MQL p, int id) {
        super(p, id);
    }

    public void render(QueryInfo qi) {

        qi.setWhereClause(walk((SimpleNode) this.children[0]));

    }

    public String walk(SimpleNode sn) {

        StringBuilder sb = new StringBuilder();

        int i = sn.jjtGetNumChildren();

        if (i > 0) {

            SimpleNode left = (SimpleNode) sn.jjtGetChild(0);

            if (left.getId() == MQLTreeConstants.JJTPATH) {
                sb.append("obj.");
                sb.append(left.stringJSForm());
            } else {
                sb.append(walk(left));
            }
        }

        sb.append(sn.stringJSForm());

        if (i > 1) {
            SimpleNode right = (SimpleNode) sn.jjtGetChild(1);

            if (right.getId() == MQLTreeConstants.JJTPATH) {
                sb.append("obj.");
                sb.append(right.stringJSForm());
            } else {
                sb.append(walk(right));
            }
        }

        return sb.toString();
    }
}
/* JavaCC - OriginalChecksum=53666b8576c10a72d9f2f4df7d4dd0ee (do not edit this line) */
