/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ed_db_DBJni */

#ifndef _Included_ed_db_DBJni
#define _Included_ed_db_DBJni
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: D */
/* Inaccessible static: EMPTY */
/* Inaccessible static: _pool */
/*
 * Class:     ed_db_DBJni
 * Method:    native_say
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_ed_db_DBJni_native_1say
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ed_db_DBJni
 * Method:    native_call
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ed_db_DBJni_native_1call
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
