/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ed_db_DBJni */

#ifndef _Included_ed_db_DBJni
#define _Included_ed_db_DBJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ed_db_DBJni
 * Method:    test1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ed_db_DBJni_test1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
