/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ed_db_DBJni */

#ifndef _Included_ed_db_DBJni
#define _Included_ed_db_DBJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ed_db_DBJni
 * Method:    msg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ed_db_DBJni_msg
  (JNIEnv *, jclass);

/*
 * Class:     ed_db_DBJni
 * Method:    insert
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_ed_db_DBJni_insert
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
