
HackTemplate = function(content) {
    this.content = content;
};
TemplateSyntaxError = function() {};

SomeException = function() { }
SomeException.prototype = {
    silent_variable_failure : true
};
SomeOtherException = function() {}


SomeClass = function() {
    this.otherclass = new OtherClass();
};
SomeClass.prototype = {
    method: function() {
        return "SomeClass.method";
    },
    method2: function(o) {
        return this.o;
    },
    method3: function() {
        throw new SomeException();
    },
    method4: function() {
        throw new SomeOtherException();
    }
};

OtherClass = function() {};
OtherClass.prototype = {
    method: function() {
        return "OtherClass.method";
    }
};
tests=[
    { name: "basic-syntax01", content: "something cool", model: {  }, results: "something cool" },
    { name: "basic-syntax02", content: "{{ headline }}", model: { "headline": "Success" }, results: "Success" },
    { name: "basic-syntax03", content: "{{ first }} --- {{ second }}", model: { "second": 2, "first": 1 }, results: "1 --- 2" },
    { name: "basic-syntax04", content: "as{{ missing }}df", model: {  }, results: [ "asdf", "asINVALIDdf" ] },
    { name: "basic-syntax06", content: "{{ multi word variable }}", model: {  }, results: TemplateSyntaxError },
    { name: "basic-syntax07", content: "{{ }}", model: {  }, results: TemplateSyntaxError },
    { name: "basic-syntax08", content: "{{        }}", model: {  }, results: TemplateSyntaxError },
    { name: "basic-syntax09", content: "{{ var.method }}", model: { "var": new SomeClass() }, results: "SomeClass.method" },
    { name: "basic-syntax10", content: "{{ var.otherclass.method }}", model: { "var": new SomeClass() }, results: "OtherClass.method" },
    { name: "basic-syntax11", content: "{{ var.blech }}", model: { "var": new SomeClass() }, results: [ "", "INVALID" ] },
    { name: "basic-syntax12", content: "{{ var.__dict__ }}", model: { "var": new SomeClass() }, results: TemplateSyntaxError },
    { name: "basic-syntax13", content: "{{ va>r }}", model: {  }, results: TemplateSyntaxError },
    { name: "basic-syntax14", content: "{{ (var.r) }}", model: {  }, results: TemplateSyntaxError },
    { name: "basic-syntax15", content: "{{ sp%am }}", model: {  }, results: TemplateSyntaxError },
    { name: "basic-syntax16", content: "{{ eggs! }}", model: {  }, results: TemplateSyntaxError },
    { name: "basic-syntax17", content: "{{ moo? }}", model: {  }, results: TemplateSyntaxError },
    { name: "basic-syntax18", content: "{{ foo.bar }}", model: { "foo": { "bar": "baz" } }, results: "baz" },
    { name: "basic-syntax19", content: "{{ foo.spam }}", model: { "foo": { "bar": "baz" } }, results: [ "", "INVALID" ] },
    { name: "basic-syntax20", content: "{{ var.method2 }}", model: { "var": new SomeClass() }, results: [ "", "INVALID" ] },
    { name: "basic-syntax21", content: "a {{ moo %} b", model: {  }, results: "a {{ moo %} b" },
    { name: "basic-syntax22", content: "{{ moo #}", model: {  }, results: "{{ moo #}" },
    { name: "basic-syntax23", content: "{{ moo #} {{ cow }}", model: { "cow": "cow" }, results: TemplateSyntaxError },
    { name: "basic-syntax24", content: "{{ moo\n }}", model: {  }, results: "{{ moo\n }}" },
    { name: "basic-syntax25", content: "{{ \"fred\" }}", model: {  }, results: "fred" },
    { name: "basic-syntax26", content: "{{ \"\\\"fred\\\"\" }}", model: {  }, results: "\"fred\"" },
    { name: "basic-syntax27", content: "{{ _(\"\\\"fred\\\"\") }}", model: {  }, results: "\"fred\"" },
    { name: "cache01", content: "{% load cache %}{% cache -1 test %}cache01{% endcache %}", model: {  }, results: "cache01" },
    { name: "cache02", content: "{% load cache %}{% cache -1 test %}cache02{% endcache %}", model: {  }, results: "cache02" },
    { name: "cache03", content: "{% load cache %}{% cache 2 test %}cache03{% endcache %}", model: {  }, results: "cache03" },
    { name: "cache04", content: "{% load cache %}{% cache 2 test %}cache04{% endcache %}", model: {  }, results: "cache03" },
    { name: "cache05", content: "{% load cache %}{% cache 2 test foo %}cache05{% endcache %}", model: { "foo": 1 }, results: "cache05" },
    { name: "cache06", content: "{% load cache %}{% cache 2 test foo %}cache06{% endcache %}", model: { "foo": 2 }, results: "cache06" },
    { name: "cache07", content: "{% load cache %}{% cache 2 test foo %}cache06{% endcache %}", model: { "foo": 1 }, results: "cache05" },
    { name: "cache08", content: "{% load cache %}{% cache %}{% endcache %}", model: {  }, results: TemplateSyntaxError },
    { name: "cache09", content: "{% load cache %}{% cache 1 %}{% endcache %}", model: {  }, results: TemplateSyntaxError },
    { name: "cache10", content: "{% load cache %}{% cache foo bar %}{% endcache %}", model: {  }, results: TemplateSyntaxError },
    { name: "comment-syntax01", content: "{# this is hidden #}hello", model: {  }, results: "hello" },
    { name: "comment-syntax02", content: "{# this is hidden #}hello{# foo #}", model: {  }, results: "hello" },
    { name: "comment-syntax03", content: "foo{#  {% if %}  #}", model: {  }, results: "foo" },
    { name: "comment-syntax04", content: "foo{#  {% endblock %}  #}", model: {  }, results: "foo" },
    { name: "comment-syntax05", content: "foo{#  {% somerandomtag %}  #}", model: {  }, results: "foo" },
    { name: "comment-syntax06", content: "foo{# {% #}", model: {  }, results: "foo" },
    { name: "comment-syntax07", content: "foo{# %} #}", model: {  }, results: "foo" },
    { name: "comment-syntax08", content: "foo{# %} #}bar", model: {  }, results: "foobar" },
    { name: "comment-syntax09", content: "foo{# {{ #}", model: {  }, results: "foo" },
    { name: "comment-syntax10", content: "foo{# }} #}", model: {  }, results: "foo" },
    { name: "comment-syntax11", content: "foo{# { #}", model: {  }, results: "foo" },
    { name: "comment-syntax12", content: "foo{# } #}", model: {  }, results: "foo" },
    { name: "comment-tag01", content: "{% comment %}this is hidden{% endcomment %}hello", model: {  }, results: "hello" },
    { name: "comment-tag02", content: "{% comment %}this is hidden{% endcomment %}hello{% comment %}foo{% endcomment %}", model: {  }, results: "hello" },
    { name: "comment-tag03", content: "foo{% comment %} {% if %} {% endcomment %}", model: {  }, results: "foo" },
    { name: "comment-tag04", content: "foo{% comment %} {% endblock %} {% endcomment %}", model: {  }, results: "foo" },
    { name: "comment-tag05", content: "foo{% comment %} {% somerandomtag %} {% endcomment %}", model: {  }, results: "foo" },
    { name: "cycle01", content: "{% cycle a %}", model: {  }, results: TemplateSyntaxError },
    { name: "cycle02", content: "{% cycle a,b,c as abc %}{% cycle abc %}", model: {  }, results: "ab" },
    { name: "cycle03", content: "{% cycle a,b,c as abc %}{% cycle abc %}{% cycle abc %}", model: {  }, results: "abc" },
    { name: "cycle04", content: "{% cycle a,b,c as abc %}{% cycle abc %}{% cycle abc %}{% cycle abc %}", model: {  }, results: "abca" },
    { name: "cycle05", content: "{% cycle %}", model: {  }, results: TemplateSyntaxError },
    { name: "cycle06", content: "{% cycle a %}", model: {  }, results: TemplateSyntaxError },
    { name: "cycle07", content: "{% cycle a,b,c as foo %}{% cycle bar %}", model: {  }, results: TemplateSyntaxError },
    { name: "cycle08", content: "{% cycle a,b,c as foo %}{% cycle foo %}{{ foo }}{{ foo }}{% cycle foo %}{{ foo }}", model: {  }, results: "abbbcc" },
    { name: "cycle09", content: "{% for i in test %}{% cycle a,b %}{{ i }},{% endfor %}", model: { "test": [ 0, 1, 2, 3, 4 ] }, results: "a0,b1,a2,b3,a4," },
    { name: "cycle10", content: "{% cycle 'a' 'b' 'c' as abc %}{% cycle abc %}", model: {  }, results: "ab" },
    { name: "cycle11", content: "{% cycle 'a' 'b' 'c' as abc %}{% cycle abc %}{% cycle abc %}", model: {  }, results: "abc" },
    { name: "cycle12", content: "{% cycle 'a' 'b' 'c' as abc %}{% cycle abc %}{% cycle abc %}{% cycle abc %}", model: {  }, results: "abca" },
    { name: "cycle13", content: "{% for i in test %}{% cycle aye bee %}{{ i }},{% endfor %}", model: { "test": [ 0, 1, 2, 3, 4 ], "aye": "a", "bee": "b" }, results: "a0,b1,a2,b3,a4," },
    { name: "cycle14", content: "{% cycle one two as foo %}{% cycle foo %}", model: { "two": "2", "one": "1" }, results: "12" },
    { name: "exception01", content: "{% extends 'nonexistent' %}", model: {  }, results: TemplateSyntaxError },
    { name: "exception02", content: "{% extends nonexistent %}", model: {  }, results: TemplateSyntaxError },
    { name: "exception03", content: "{% extends 'inheritance01' %}{% block first %}2{% endblock %}{% extends 'inheritance16' %}", model: {  }, results: TemplateSyntaxError },
    { name: "exception04", content: "{% extends 'inheritance17' %}{% block first %}{% echo 400 %}5678{% endblock %}", model: {  }, results: TemplateSyntaxError },
    { name: "filter-syntax01", content: "{{ var|upper }}", model: { "var": "Django is the greatest!" }, results: "DJANGO IS THE GREATEST!" },
    { name: "filter-syntax02", content: "{{ var|upper|lower }}", model: { "var": "Django is the greatest!" }, results: "django is the greatest!" },
    { name: "filter-syntax03", content: "{{ var |upper }}", model: {  }, results: TemplateSyntaxError },
    { name: "filter-syntax04", content: "{{ var| upper }}", model: {  }, results: TemplateSyntaxError },
    { name: "filter-syntax05", content: "{{ var|does_not_exist }}", model: {  }, results: TemplateSyntaxError },
    { name: "filter-syntax06", content: "{{ var|fil(ter) }}", model: {  }, results: TemplateSyntaxError },
    { name: "filter-syntax07", content: "{% nothing_to_see_here %}", model: {  }, results: TemplateSyntaxError },
    { name: "filter-syntax08", content: "{% %}", model: {  }, results: TemplateSyntaxError },
    { name: "filter-syntax09", content: "{{ var|removetags:\"b i\"|upper|lower }}", model: { "var": "<b><i>Yes</i></b>" }, results: "yes" },
    { name: "filter-syntax10", content: "{{ var|default_if_none:\" endquote\\\" hah\" }}", model: { "var": null }, results: " endquote\" hah" },
    { name: "filter-syntax11", content: "{{ var|default_if_none:var2 }}", model: { "var": null, "var2": "happy" }, results: "happy" },
    { name: "filter-syntax12", content: "{{ var|yesno:\"yup,nup,mup\" }} {{ var|yesno }}", model: { "var": 1 }, results: "yup yes" },
    { name: "filter-syntax13", content: "1{{ var.method3 }}2", model: { "var": new SomeClass() }, results: [ "12", "1INVALID2" ] },
    { name: "filter-syntax14", content: "1{{ var.method4 }}2", model: { "var": new SomeClass() }, results: SomeOtherException },
    { name: "filter-syntax15", content: "{{ var|default_if_none:\"foo\\bar\" }}", model: { "var": null }, results: "foo\\bar" },
    { name: "filter-syntax16", content: "{{ var|default_if_none:\"foo\\now\" }}", model: { "var": null }, results: "foo\\now" },
    { name: "filter-syntax17", content: "{{ var|join:\"\" }}", model: { "var": [ "a", "b", "c" ] }, results: "abc" },
    { name: "filter-syntax19", content: "{{ var|truncatewords:1 }}", model: { "var": "hello world" }, results: "hello ..." },
    { name: "filter01", content: "{% filter upper %}{% endfilter %}", model: {  }, results: "" },
    { name: "filter02", content: "{% filter upper %}django{% endfilter %}", model: {  }, results: "DJANGO" },
    { name: "filter03", content: "{% filter upper|lower %}django{% endfilter %}", model: {  }, results: "django" },
    { name: "filter04", content: "{% filter cut:remove %}djangospam{% endfilter %}", model: { "remove": "spam" }, results: "django" },
    { name: "firstof01", content: "{% firstof a b c %}", model: { "a": 0, "c": 0, "b": 0 }, results: "" },
    { name: "firstof02", content: "{% firstof a b c %}", model: { "a": 1, "c": 0, "b": 0 }, results: "1" },
    { name: "firstof03", content: "{% firstof a b c %}", model: { "a": 0, "c": 0, "b": 2 }, results: "2" },
    { name: "firstof04", content: "{% firstof a b c %}", model: { "a": 0, "c": 3, "b": 0 }, results: "3" },
    { name: "firstof05", content: "{% firstof a b c %}", model: { "a": 1, "c": 3, "b": 2 }, results: "1" },
    { name: "firstof06", content: "{% firstof a b c %}", model: { "c": 3, "b": 0 }, results: "3" },
    { name: "firstof07", content: "{% firstof a b \"c\" %}", model: { "a": 0 }, results: "c" },
    { name: "firstof08", content: "{% firstof a b \"c and d\" %}", model: { "a": 0, "b": 0 }, results: "c and d" },
    { name: "firstof09", content: "{% firstof %}", model: {  }, results: TemplateSyntaxError },
    { name: "for-tag-vars01", content: "{% for val in values %}{{ forloop.counter }}{% endfor %}", model: { "values": [ 6, 6, 6 ] }, results: "123" },
    { name: "for-tag-vars02", content: "{% for val in values %}{{ forloop.counter0 }}{% endfor %}", model: { "values": [ 6, 6, 6 ] }, results: "012" },
    { name: "for-tag-vars03", content: "{% for val in values %}{{ forloop.revcounter }}{% endfor %}", model: { "values": [ 6, 6, 6 ] }, results: "321" },
    { name: "for-tag-vars04", content: "{% for val in values %}{{ forloop.revcounter0 }}{% endfor %}", model: { "values": [ 6, 6, 6 ] }, results: "210" },
    { name: "for-tag-vars05", content: "{% for val in values %}{% if forloop.first %}f{% else %}x{% endif %}{% endfor %}", model: { "values": [ 6, 6, 6 ] }, results: "fxx" },
    { name: "for-tag-vars06", content: "{% for val in values %}{% if forloop.last %}l{% else %}x{% endif %}{% endfor %}", model: { "values": [ 6, 6, 6 ] }, results: "xxl" },
    { name: "for-tag01", content: "{% for val in values %}{{ val }}{% endfor %}", model: { "values": [ 1, 2, 3 ] }, results: "123" },
    { name: "for-tag02", content: "{% for val in values reversed %}{{ val }}{% endfor %}", model: { "values": [ 1, 2, 3 ] }, results: "321" },
    { name: "if-tag-and01", content: "{% if foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 1 }, results: "yes" },
    { name: "if-tag-and02", content: "{% if foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 0 }, results: "no" },
    { name: "if-tag-and03", content: "{% if foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 1 }, results: "no" },
    { name: "if-tag-and04", content: "{% if foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 0 }, results: "no" },
    { name: "if-tag-and05", content: "{% if foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 0 }, results: "no" },
    { name: "if-tag-and06", content: "{% if foo and bar %}yes{% else %}no{% endif %}", model: { "bar": 0 }, results: "no" },
    { name: "if-tag-and07", content: "{% if foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 1 }, results: "no" },
    { name: "if-tag-and08", content: "{% if foo and bar %}yes{% else %}no{% endif %}", model: { "bar": 1 }, results: "no" },
    { name: "if-tag-error01", content: "{% if foo or bar and baz %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 0 }, results: TemplateSyntaxError },
    { name: "if-tag-error02", content: "{% if foo and %}yes{% else %}no{% endif %}", model: { "foo": 1 }, results: TemplateSyntaxError },
    { name: "if-tag-error03", content: "{% if foo or %}yes{% else %}no{% endif %}", model: { "foo": 1 }, results: TemplateSyntaxError },
    { name: "if-tag-error04", content: "{% if not foo and %}yes{% else %}no{% endif %}", model: { "foo": 1 }, results: TemplateSyntaxError },
    { name: "if-tag-error05", content: "{% if not foo or %}yes{% else %}no{% endif %}", model: { "foo": 1 }, results: TemplateSyntaxError },
    { name: "if-tag-not01", content: "{% if not foo %}no{% else %}yes{% endif %}", model: { "foo": 1 }, results: "yes" },
    { name: "if-tag-not02", content: "{% if not %}yes{% else %}no{% endif %}", model: { "foo": 1 }, results: "no" },
    { name: "if-tag-not03", content: "{% if not %}yes{% else %}no{% endif %}", model: { "not": 1 }, results: "yes" },
    { name: "if-tag-not04", content: "{% if not not %}no{% else %}yes{% endif %}", model: { "not": 1 }, results: "yes" },
    { name: "if-tag-not05", content: "{% if not not %}no{% else %}yes{% endif %}", model: {  }, results: "no" },
    { name: "if-tag-not06", content: "{% if foo and not bar %}yes{% else %}no{% endif %}", model: {  }, results: "no" },
    { name: "if-tag-not07", content: "{% if foo and not bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 1 }, results: "no" },
    { name: "if-tag-not08", content: "{% if foo and not bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 0 }, results: "yes" },
    { name: "if-tag-not09", content: "{% if foo and not bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 1 }, results: "no" },
    { name: "if-tag-not10", content: "{% if foo and not bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 0 }, results: "no" },
    { name: "if-tag-not11", content: "{% if not foo and bar %}yes{% else %}no{% endif %}", model: {  }, results: "no" },
    { name: "if-tag-not12", content: "{% if not foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 1 }, results: "no" },
    { name: "if-tag-not13", content: "{% if not foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 0 }, results: "no" },
    { name: "if-tag-not14", content: "{% if not foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 1 }, results: "yes" },
    { name: "if-tag-not15", content: "{% if not foo and bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 0 }, results: "no" },
    { name: "if-tag-not16", content: "{% if foo or not bar %}yes{% else %}no{% endif %}", model: {  }, results: "yes" },
    { name: "if-tag-not17", content: "{% if foo or not bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 1 }, results: "yes" },
    { name: "if-tag-not18", content: "{% if foo or not bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 0 }, results: "yes" },
    { name: "if-tag-not19", content: "{% if foo or not bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 1 }, results: "no" },
    { name: "if-tag-not20", content: "{% if foo or not bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 0 }, results: "yes" },
    { name: "if-tag-not21", content: "{% if not foo or bar %}yes{% else %}no{% endif %}", model: {  }, results: "yes" },
    { name: "if-tag-not22", content: "{% if not foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 1 }, results: "yes" },
    { name: "if-tag-not23", content: "{% if not foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 0 }, results: "no" },
    { name: "if-tag-not24", content: "{% if not foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 1 }, results: "yes" },
    { name: "if-tag-not25", content: "{% if not foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 0 }, results: "yes" },
    { name: "if-tag-not26", content: "{% if not foo and not bar %}yes{% else %}no{% endif %}", model: {  }, results: "yes" },
    { name: "if-tag-not27", content: "{% if not foo and not bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 1 }, results: "no" },
    { name: "if-tag-not28", content: "{% if not foo and not bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 0 }, results: "no" },
    { name: "if-tag-not29", content: "{% if not foo and not bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 1 }, results: "no" },
    { name: "if-tag-not30", content: "{% if not foo and not bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 0 }, results: "yes" },
    { name: "if-tag-not31", content: "{% if not foo or not bar %}yes{% else %}no{% endif %}", model: {  }, results: "yes" },
    { name: "if-tag-not32", content: "{% if not foo or not bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 1 }, results: "no" },
    { name: "if-tag-not33", content: "{% if not foo or not bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 0 }, results: "yes" },
    { name: "if-tag-not34", content: "{% if not foo or not bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 1 }, results: "yes" },
    { name: "if-tag-not35", content: "{% if not foo or not bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 0 }, results: "yes" },
    { name: "if-tag-or01", content: "{% if foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 1 }, results: "yes" },
    { name: "if-tag-or02", content: "{% if foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 1, "bar": 0 }, results: "yes" },
    { name: "if-tag-or03", content: "{% if foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 1 }, results: "yes" },
    { name: "if-tag-or04", content: "{% if foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 0, "bar": 0 }, results: "no" },
    { name: "if-tag-or05", content: "{% if foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 0 }, results: "no" },
    { name: "if-tag-or06", content: "{% if foo or bar %}yes{% else %}no{% endif %}", model: { "bar": 0 }, results: "no" },
    { name: "if-tag-or07", content: "{% if foo or bar %}yes{% else %}no{% endif %}", model: { "foo": 1 }, results: "yes" },
    { name: "if-tag-or08", content: "{% if foo or bar %}yes{% else %}no{% endif %}", model: { "bar": 1 }, results: "yes" },
    { name: "if-tag01", content: "{% if foo %}yes{% else %}no{% endif %}", model: { "foo": 1 }, results: "yes" },
    { name: "if-tag02", content: "{% if foo %}yes{% else %}no{% endif %}", model: { "foo": 0 }, results: "no" },
    { name: "if-tag03", content: "{% if foo %}yes{% else %}no{% endif %}", model: {  }, results: "no" },
    { name: "ifchanged-param01", content: "{% for n in num %}{% ifchanged n %}..{% endifchanged %}{{ n }}{% endfor %}", model: { "num": [ 1, 2, 3 ] }, results: "..1..2..3" },
    { name: "ifchanged-param02", content: "{% for n in num %}{% for x in numx %}{% ifchanged n %}..{% endifchanged %}{{ x }}{% endfor %}{% endfor %}", model: { "num": [ 1, 2, 3 ], "numx": [ 5, 6, 7 ] }, results: "..567..567..567" },
    { name: "ifchanged-param03", content: "{% for n in num %}{{ n }}{% for x in numx %}{% ifchanged x n %}{{ x }}{% endifchanged %}{% endfor %}{% endfor %}", model: { "num": [ 1, 1, 2 ], "numx": [ 5, 6, 6 ] }, results: "156156256" },
    { name: "ifchanged-param04", content: "{% for d in days %}{% ifchanged d.day %}{{ d.day }}{% endifchanged %}{% for h in d.hours %}{% ifchanged d.day h %}{{ h }}{% endifchanged %}{% endfor %}{% endfor %}", model: { "days": [ { "hours": [ 1, 2, 3 ], "day": 1 }, { "hours": [ 3 ], "day": 2 } ] }, results: "112323" },
    { name: "ifchanged01", content: "{% for n in num %}{% ifchanged %}{{ n }}{% endifchanged %}{% endfor %}", model: { "num": [ 1, 2, 3 ] }, results: "123" },
    { name: "ifchanged02", content: "{% for n in num %}{% ifchanged %}{{ n }}{% endifchanged %}{% endfor %}", model: { "num": [ 1, 1, 3 ] }, results: "13" },
    { name: "ifchanged03", content: "{% for n in num %}{% ifchanged %}{{ n }}{% endifchanged %}{% endfor %}", model: { "num": [ 1, 1, 1 ] }, results: "1" },
    { name: "ifchanged04", content: "{% for n in num %}{% ifchanged %}{{ n }}{% endifchanged %}{% for x in numx %}{% ifchanged %}{{ x }}{% endifchanged %}{% endfor %}{% endfor %}", model: { "num": [ 1, 2, 3 ], "numx": [ 2, 2, 2 ] }, results: "122232" },
    { name: "ifchanged05", content: "{% for n in num %}{% ifchanged %}{{ n }}{% endifchanged %}{% for x in numx %}{% ifchanged %}{{ x }}{% endifchanged %}{% endfor %}{% endfor %}", model: { "num": [ 1, 1, 1 ], "numx": [ 1, 2, 3 ] }, results: "1123123123" },
    { name: "ifchanged06", content: "{% for n in num %}{% ifchanged %}{{ n }}{% endifchanged %}{% for x in numx %}{% ifchanged %}{{ x }}{% endifchanged %}{% endfor %}{% endfor %}", model: { "num": [ 1, 1, 1 ], "numx": [ 2, 2, 2 ] }, results: "1222" },
    { name: "ifchanged07", content: "{% for n in num %}{% ifchanged %}{{ n }}{% endifchanged %}{% for x in numx %}{% ifchanged %}{{ x }}{% endifchanged %}{% for y in numy %}{% ifchanged %}{{ y }}{% endifchanged %}{% endfor %}{% endfor %}{% endfor %}", model: { "num": [ 1, 1, 1 ], "numx": [ 2, 2, 2 ], "numy": [ 3, 3, 3 ] }, results: "1233323332333" },
    { name: "ifequal-numeric01", content: "{% ifequal x 5 %}yes{% endifequal %}", model: { "x": "5" }, results: "" },
    { name: "ifequal-numeric02", content: "{% ifequal x 5 %}yes{% endifequal %}", model: { "x": 5 }, results: "yes" },
    { name: "ifequal-numeric03", content: "{% ifequal x 5.2 %}yes{% endifequal %}", model: { "x": 5 }, results: "" },
    { name: "ifequal-numeric04", content: "{% ifequal x 5.2 %}yes{% endifequal %}", model: { "x": 5 }, results: "yes" },
    { name: "ifequal-numeric05", content: "{% ifequal x 0.2 %}yes{% endifequal %}", model: { "x": 0 }, results: "yes" },
    { name: "ifequal-numeric06", content: "{% ifequal x .2 %}yes{% endifequal %}", model: { "x": 0 }, results: "yes" },
    { name: "ifequal-numeric07", content: "{% ifequal x 2. %}yes{% endifequal %}", model: { "x": 2 }, results: "" },
    { name: "ifequal-numeric08", content: "{% ifequal x \"5\" %}yes{% endifequal %}", model: { "x": 5 }, results: "" },
    { name: "ifequal-numeric09", content: "{% ifequal x \"5\" %}yes{% endifequal %}", model: { "x": "5" }, results: "yes" },
    { name: "ifequal-numeric10", content: "{% ifequal x -5 %}yes{% endifequal %}", model: { "x": -5 }, results: "yes" },
    { name: "ifequal-numeric11", content: "{% ifequal x -5.2 %}yes{% endifequal %}", model: { "x": -5 }, results: "yes" },
    { name: "ifequal-numeric12", content: "{% ifequal x +5 %}yes{% endifequal %}", model: { "x": 5 }, results: "yes" },
    { name: "ifequal-split01", content: "{% ifequal a \"test man\" %}yes{% else %}no{% endifequal %}", model: {  }, results: "no" },
    { name: "ifequal-split02", content: "{% ifequal a \"test man\" %}yes{% else %}no{% endifequal %}", model: { "a": "foo" }, results: "no" },
    { name: "ifequal-split03", content: "{% ifequal a \"test man\" %}yes{% else %}no{% endifequal %}", model: { "a": "test man" }, results: "yes" },
    { name: "ifequal-split04", content: "{% ifequal a 'test man' %}yes{% else %}no{% endifequal %}", model: { "a": "test man" }, results: "yes" },
    { name: "ifequal-split05", content: "{% ifequal a 'i \"love\" you' %}yes{% else %}no{% endifequal %}", model: { "a": "" }, results: "no" },
    { name: "ifequal-split06", content: "{% ifequal a 'i \"love\" you' %}yes{% else %}no{% endifequal %}", model: { "a": "i \"love\" you" }, results: "yes" },
    { name: "ifequal-split07", content: "{% ifequal a 'i \"love\" you' %}yes{% else %}no{% endifequal %}", model: { "a": "i love you" }, results: "no" },
    { name: "ifequal-split08", content: "{% ifequal a 'I\\'m happy' %}yes{% else %}no{% endifequal %}", model: { "a": "I'm happy" }, results: "yes" },
    { name: "ifequal-split09", content: "{% ifequal a 'slash\\man' %}yes{% else %}no{% endifequal %}", model: { "a": "slash\\man" }, results: "yes" },
    { name: "ifequal-split10", content: "{% ifequal a 'slash\\man' %}yes{% else %}no{% endifequal %}", model: { "a": "slashman" }, results: "no" },
    { name: "ifequal01", content: "{% ifequal a b %}yes{% endifequal %}", model: { "a": 1, "b": 2 }, results: "" },
    { name: "ifequal02", content: "{% ifequal a b %}yes{% endifequal %}", model: { "a": 1, "b": 1 }, results: "yes" },
    { name: "ifequal03", content: "{% ifequal a b %}yes{% else %}no{% endifequal %}", model: { "a": 1, "b": 2 }, results: "no" },
    { name: "ifequal04", content: "{% ifequal a b %}yes{% else %}no{% endifequal %}", model: { "a": 1, "b": 1 }, results: "yes" },
    { name: "ifequal05", content: "{% ifequal a 'test' %}yes{% else %}no{% endifequal %}", model: { "a": "test" }, results: "yes" },
    { name: "ifequal06", content: "{% ifequal a 'test' %}yes{% else %}no{% endifequal %}", model: { "a": "no" }, results: "no" },
    { name: "ifequal07", content: "{% ifequal a \"test\" %}yes{% else %}no{% endifequal %}", model: { "a": "test" }, results: "yes" },
    { name: "ifequal08", content: "{% ifequal a \"test\" %}yes{% else %}no{% endifequal %}", model: { "a": "no" }, results: "no" },
    { name: "ifequal09", content: "{% ifequal a \"test\" %}yes{% else %}no{% endifequal %}", model: {  }, results: "no" },
    { name: "ifequal10", content: "{% ifequal a b %}yes{% else %}no{% endifequal %}", model: {  }, results: "yes" },
    { name: "ifnotequal01", content: "{% ifnotequal a b %}yes{% endifnotequal %}", model: { "a": 1, "b": 2 }, results: "yes" },
    { name: "ifnotequal02", content: "{% ifnotequal a b %}yes{% endifnotequal %}", model: { "a": 1, "b": 1 }, results: "" },
    { name: "ifnotequal03", content: "{% ifnotequal a b %}yes{% else %}no{% endifnotequal %}", model: { "a": 1, "b": 2 }, results: "yes" },
    { name: "ifnotequal04", content: "{% ifnotequal a b %}yes{% else %}no{% endifnotequal %}", model: { "a": 1, "b": 1 }, results: "no" },
    { name: "include01", content: "{% include \"basic-syntax01\" %}", model: {  }, results: "something cool" },
    { name: "include02", content: "{% include \"basic-syntax02\" %}", model: { "headline": "Included" }, results: "Included" },
    { name: "include03", content: "{% include template_name %}", model: { "headline": "Included", "template_name": "basic-syntax02" }, results: "Included" },
    { name: "include04", content: "a{% include \"nonexistent\" %}b", model: {  }, results: "ab" },
    { name: "inheritance01", content: "1{% block first %}&{% endblock %}3{% block second %}_{% endblock %}", model: {  }, results: "1&3_" },
    { name: "inheritance02", content: "{% extends 'inheritance01' %}{% block first %}2{% endblock %}{% block second %}4{% endblock %}", model: {  }, results: "1234" },
    { name: "inheritance03", content: "{% extends 'inheritance02' %}", model: {  }, results: "1234" },
    { name: "inheritance04", content: "{% extends 'inheritance01' %}", model: {  }, results: "1&3_" },
    { name: "inheritance05", content: "{% extends \"inheritance02\" %}", model: {  }, results: "1234" },
    { name: "inheritance06", content: "{% extends foo %}", model: { "foo": "inheritance02" }, results: "1234" },
    { name: "inheritance07", content: "{% extends 'inheritance01' %}{% block second %}5{% endblock %}", model: {  }, results: "1&35" },
    { name: "inheritance08", content: "{% extends 'inheritance02' %}{% block second %}5{% endblock %}", model: {  }, results: "1235" },
    { name: "inheritance09", content: "{% extends 'inheritance04' %}", model: {  }, results: "1&3_" },
    { name: "inheritance10", content: "{% extends 'inheritance04' %}      ", model: {  }, results: "1&3_" },
    { name: "inheritance11", content: "{% extends 'inheritance04' %}{% block first %}2{% endblock %}{% block second %}4{% endblock %}", model: {  }, results: "1234" },
    { name: "inheritance12", content: "{% extends 'inheritance07' %}{% block first %}2{% endblock %}", model: {  }, results: "1235" },
    { name: "inheritance13", content: "{% extends 'inheritance02' %}{% block first %}a{% endblock %}{% block second %}b{% endblock %}", model: {  }, results: "1a3b" },
    { name: "inheritance14", content: "{% extends 'inheritance01' %}{% block newblock %}NO DISPLAY{% endblock %}", model: {  }, results: "1&3_" },
    { name: "inheritance15", content: "{% extends 'inheritance01' %}{% block first %}2{% block inner %}inner{% endblock %}{% endblock %}", model: {  }, results: "12inner3_" },
    { name: "inheritance16", content: "{% extends 'inheritance15' %}{% block inner %}out{% endblock %}", model: {  }, results: "12out3_" },
    { name: "inheritance17", content: "{% load testtags %}{% block first %}1234{% endblock %}", model: {  }, results: "1234" },
    { name: "inheritance18", content: "{% load testtags %}{% echo this that theother %}5678", model: {  }, results: "this that theother5678" },
    { name: "inheritance19", content: "{% extends 'inheritance01' %}{% block first %}{% load testtags %}{% echo 400 %}5678{% endblock %}", model: {  }, results: "140056783_" },
    { name: "inheritance20", content: "{% extends 'inheritance01' %}{% block first %}{{ block.super }}a{% endblock %}", model: {  }, results: "1&a3_" },
    { name: "inheritance21", content: "{% extends 'inheritance02' %}{% block first %}{{ block.super }}a{% endblock %}", model: {  }, results: "12a34" },
    { name: "inheritance22", content: "{% extends 'inheritance04' %}{% block first %}{{ block.super }}a{% endblock %}", model: {  }, results: "1&a3_" },
    { name: "inheritance23", content: "{% extends 'inheritance20' %}{% block first %}{{ block.super }}b{% endblock %}", model: {  }, results: "1&ab3_" },
    { name: "inheritance24", content: "{% extends context_template %}{% block first %}2{% endblock %}{% block second %}4{% endblock %}", model: { "context_template": new HackTemplate("1{% block first %}_{% endblock %}3{% block second %}_{% endblock %}") }, results: "1234" },
    { name: "inheritance25", content: "{% extends context_template.1 %}{% block first %}2{% endblock %}{% block second %}4{% endblock %}", model: { "context_template": [ new HackTemplate("Wrong"), new HackTemplate("1{% block first %}_{% endblock %}3{% block second %}_{% endblock %}") ] }, results: "1234" },
    { name: "inheritance26", content: "no tags", model: {  }, results: "no tags" },
    { name: "inheritance27", content: "{% extends 'inheritance26' %}", model: {  }, results: "no tags" },
    { name: "invalidstr01", content: "{{ var|default:\"Foo\" }}", model: {  }, results: [ "Foo", "INVALID" ] },
    { name: "invalidstr02", content: "{{ var|default_if_none:\"Foo\" }}", model: {  }, results: [ "", "INVALID" ] },
    { name: "invalidstr03", content: "{% for v in var %}({{ v }}){% endfor %}", model: {  }, results: "" },
    { name: "invalidstr04", content: "{% if var|default:\"Foo\" %}Yes{% else %}No{% endif %}", model: {  }, results: "Yes" },
    { name: "invalidstr05", content: "{{ var }}", model: {  }, results: [ "", "INVALID %s", "var" ] },
    { name: "invalidstr06", content: "{{ var.prop }}", model: { "var": {  } }, results: [ "", "INVALID %s", "var.prop" ] },
    { name: "list-index01", content: "{{ var.1 }}", model: { "var": [ "first item", "second item" ] }, results: "second item" },
    { name: "list-index02", content: "{{ var.5 }}", model: { "var": [ "first item", "second item" ] }, results: [ "", "INVALID" ] },
    { name: "list-index03", content: "{{ var.1 }}", model: { "var": null }, results: [ "", "INVALID" ] },
    { name: "list-index04", content: "{{ var.1 }}", model: { "var": {  } }, results: [ "", "INVALID" ] },
    { name: "list-index05", content: "{{ var.1 }}", model: { "var": { "1": "hello" } }, results: "hello" },
    { name: "list-index06", content: "{{ var.1 }}", model: { "var": { 1: "hello" } }, results: "hello" },
    { name: "list-index07", content: "{{ var.1 }}", model: { "var": { "1": "hello", 1: "world" } }, results: "hello" },
    { name: "multiline01", content: "\n                            Hello,\n                            boys.\n                            How\n                            are\n                            you\n                            gentlemen.\n                            ", model: {  }, results: "\n                            Hello,\n                            boys.\n                            How\n                            are\n                            you\n                            gentlemen.\n                            " },
    { name: "namedendblocks01", content: "1{% block first %}_{% block second %}2{% endblock second %}_{% endblock first %}3", model: {  }, results: "1_2_3" },
    { name: "namedendblocks02", content: "1{% block first %}_{% block second %}2{% endblock first %}_{% endblock second %}3", model: {  }, results: TemplateSyntaxError },
    { name: "namedendblocks03", content: "1{% block first %}_{% block second %}2{% endblock %}_{% endblock second %}3", model: {  }, results: TemplateSyntaxError },
    { name: "namedendblocks04", content: "1{% block first %}_{% block second %}2{% endblock second %}_{% endblock third %}3", model: {  }, results: TemplateSyntaxError },
    { name: "namedendblocks05", content: "1{% block first %}_{% block second %}2{% endblock first %}", model: {  }, results: TemplateSyntaxError },
    { name: "namedendblocks06", content: "1{% block first %}_{% block second %}2{% endblock %}_{% endblock first %}3", model: {  }, results: "1_2_3" },
    { name: "namedendblocks07", content: "1{% block first %}_{% block second %}2{% endblock second %}_{% endblock %}3", model: {  }, results: "1_2_3" },
    { name: "now01", content: "{% now \"j n Y\"%}", model: {  }, results: "26 6 2008" },
    { name: "now02", content: "{% now \"j \"n\" Y\"%}", model: {  }, results: TemplateSyntaxError },
    { name: "regroup01", content: "{% regroup data by bar as grouped %}{% for group in grouped %}{{ group.grouper }}:{% for item in group.list %}{{ item.foo }}{% endfor %},{% endfor %}", model: { "data": [ { "foo": "c", "bar": 1 }, { "foo": "d", "bar": 1 }, { "foo": "a", "bar": 2 }, { "foo": "b", "bar": 2 }, { "foo": "x", "bar": 3 } ] }, results: "1:cd,2:ab,3:x," },
    { name: "regroup02", content: "{% regroup data by bar as grouped %}{% for group in grouped %}{{ group.grouper }}:{% for item in group.list %}{{ item.foo }}{% endfor %},{% endfor %}", model: {  }, results: "" },
    { name: "spaceless01", content: "{% spaceless %} <b>    <i> text </i>    </b> {% endspaceless %}", model: {  }, results: "<b><i> text </i></b>" },
    { name: "spaceless02", content: "{% spaceless %} <b> \n <i> text </i> \n </b> {% endspaceless %}", model: {  }, results: "<b><i> text </i></b>" },
    { name: "spaceless03", content: "{% spaceless %}<b><i>text</i></b>{% endspaceless %}", model: {  }, results: "<b><i>text</i></b>" },
    { name: "templatetag01", content: "{% templatetag openblock %}", model: {  }, results: "{%" },
    { name: "templatetag02", content: "{% templatetag closeblock %}", model: {  }, results: "%}" },
    { name: "templatetag03", content: "{% templatetag openvariable %}", model: {  }, results: "{{" },
    { name: "templatetag04", content: "{% templatetag closevariable %}", model: {  }, results: "}}" },
    { name: "templatetag05", content: "{% templatetag %}", model: {  }, results: TemplateSyntaxError },
    { name: "templatetag06", content: "{% templatetag foo %}", model: {  }, results: TemplateSyntaxError },
    { name: "templatetag07", content: "{% templatetag openbrace %}", model: {  }, results: "{" },
    { name: "templatetag08", content: "{% templatetag closebrace %}", model: {  }, results: "}" },
    { name: "templatetag09", content: "{% templatetag openbrace %}{% templatetag openbrace %}", model: {  }, results: "{{" },
    { name: "templatetag10", content: "{% templatetag closebrace %}{% templatetag closebrace %}", model: {  }, results: "}}" },
    { name: "templatetag11", content: "{% templatetag opencomment %}", model: {  }, results: "{#" },
    { name: "templatetag12", content: "{% templatetag closecomment %}", model: {  }, results: "#}" },
    { name: "url-fail01", content: "{% url %}", model: {  }, results: TemplateSyntaxError },
    { name: "url-fail02", content: "{% url no_such_view %}", model: {  }, results: "" },
    { name: "url-fail03", content: "{% url regressiontests.templates.views.client no_such_param=\"value\" %}", model: {  }, results: "" },
    { name: "url01", content: "{% url regressiontests.templates.views.client client.id %}", model: { "client": { "id": 1 } }, results: "/url_tag/client/1/" },
    { name: "url02", content: "{% url regressiontests.templates.views.client_action client.id, action=\"update\" %}", model: { "client": { "id": 1 } }, results: "/url_tag/client/1/update/" },
    { name: "url03", content: "{% url regressiontests.templates.views.index %}", model: {  }, results: "/url_tag/" },
    { name: "url04", content: "{% url named.client client.id %}", model: { "client": { "id": 1 } }, results: "/url_tag/named-client/1/" },
    { name: "widthratio01", content: "{% widthratio a b 0 %}", model: { "a": 50, "b": 100 }, results: "0" },
    { name: "widthratio02", content: "{% widthratio a b 100 %}", model: { "a": 0, "b": 0 }, results: "" },
    { name: "widthratio03", content: "{% widthratio a b 100 %}", model: { "a": 0, "b": 100 }, results: "0" },
    { name: "widthratio04", content: "{% widthratio a b 100 %}", model: { "a": 50, "b": 100 }, results: "50" },
    { name: "widthratio05", content: "{% widthratio a b 100 %}", model: { "a": 100, "b": 100 }, results: "100" },
    { name: "widthratio06", content: "{% widthratio a b 100 %}", model: { "a": 50, "b": 80 }, results: "63" },
    { name: "widthratio07", content: "{% widthratio a b 100 %}", model: { "a": 50, "b": 70 }, results: "71" },
    { name: "widthratio08", content: "{% widthratio %}", model: {  }, results: TemplateSyntaxError },
    { name: "widthratio09", content: "{% widthratio a b %}", model: { "a": 50, "b": 100 }, results: TemplateSyntaxError },
    { name: "widthratio10", content: "{% widthratio a b 100.0 %}", model: { "a": 50, "b": 100 }, results: TemplateSyntaxError },
    { name: "with-error01", content: "{% with dict.key xx key %}{{ key }}{% endwith %}", model: { "dict": { "key": 50 } }, results: TemplateSyntaxError },
    { name: "with-error02", content: "{% with dict.key as %}{{ key }}{% endwith %}", model: { "dict": { "key": 50 } }, results: TemplateSyntaxError },
    { name: "with01", content: "{% with dict.key as key %}{{ key }}{% endwith %}", model: { "dict": { "key": 50 } }, results: "50" },
    { name: "with02", content: "{{ key }}{% with dict.key as key %}{{ key }}-{{ dict.key }}-{{ key }}{% endwith %}{{ key }}", model: { "dict": { "key": 50 } }, results: [ "50-50-50", "INVALID50-50-50INVALID" ] },

];
