--- !ruby/object:RI::ClassDescription 
includes: 
- !ruby/object:RI::IncludedModule 
  name: TaskManager
name: Application
constants: 
- !ruby/object:RI::Constant 
  name: DEFAULT_RAKEFILES
  value: '[''rakefile'', ''Rakefile'', ''rakefile.rb'', ''Rakefile.rb''].freeze'
  comment: 
- !ruby/object:RI::Constant 
  name: OPTIONS
  value: '[     # :nodoc:       [''--classic-namespace'', ''-C'', GetoptLong::NO_ARGUMENT,         "Put
    Task and FileTask in the top level namespace"],       [''--describe'',  ''-D'',
    GetoptLong::OPTIONAL_ARGUMENT,         "Describe the tasks (matching optional
    PATTERN), then exit."],       [''--rakefile'', ''-f'', GetoptLong::OPTIONAL_ARGUMENT,         "Use
    FILE as the rakefile."],       [''--help'',     ''-h'', ''-H'', GetoptLong::NO_ARGUMENT,         "Display
    this help message."],       [''--libdir'',   ''-I'', GetoptLong::REQUIRED_ARGUMENT,         "Include
    LIBDIR in the search path for required modules."],       [''--dry-run'',  ''-n'',
    GetoptLong::NO_ARGUMENT,         "Do a dry run without executing actions."],       [''--nosearch'',
    ''-N'', GetoptLong::NO_ARGUMENT,         "Do not search parent directories for
    the Rakefile."],       [''--prereqs'',  ''-P'', GetoptLong::NO_ARGUMENT,         "Display
    the tasks and dependencies, then exit."],       [''--quiet'',    ''-q'', GetoptLong::NO_ARGUMENT,         "Do
    not log messages to standard output."],       [''--require'',  ''-r'', GetoptLong::REQUIRED_ARGUMENT,         "Require
    MODULE before executing rakefile."],       [''--rakelibdir'', ''-R'', GetoptLong::REQUIRED_ARGUMENT,         "Auto-import
    any .rake files in RAKELIBDIR. (default is ''rakelib'')"],       [''--silent'',   ''-s'',
    GetoptLong::NO_ARGUMENT,         "Like --quiet, but also suppresses the ''in directory''
    announcement."],       [''--tasks'',    ''-T'', GetoptLong::OPTIONAL_ARGUMENT,         "Display
    the tasks (matching optional PATTERN) with descriptions, then exit."],       [''--trace'',    ''-t'',
    GetoptLong::NO_ARGUMENT,         "Turn on invoke/execute tracing, enable full
    backtrace."],       [''--verbose'',  ''-v'', GetoptLong::NO_ARGUMENT,         "Log
    message to standard output (default)."],       [''--version'',  ''-V'', GetoptLong::NO_ARGUMENT,         "Display
    the program version."],     ]'
  comment: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Rake main application object. When invoking <tt>rake</tt> from the command
    line, a Rake::Application object is created and run.
attributes: 
- !ruby/object:RI::Attribute 
  name: name
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: The name of the application (typically 'rake')
  rw: R
- !ruby/object:RI::Attribute 
  name: original_dir
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: The original directory where rake was invoked.
  rw: R
- !ruby/object:RI::Attribute 
  name: rakefile
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: Name of the actual rakefile used.
  rw: R
- !ruby/object:RI::Attribute 
  name: top_level_tasks
  comment: 
  - !ruby/struct:SM::Flow::P 
    body: List of the top level task names (task names from the command line).
  rw: R
instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: add_import
- !ruby/object:RI::MethodSummary 
  name: add_loader
- !ruby/object:RI::MethodSummary 
  name: collect_tasks
- !ruby/object:RI::MethodSummary 
  name: command_line_options
- !ruby/object:RI::MethodSummary 
  name: const_warning
- !ruby/object:RI::MethodSummary 
  name: display_prerequisites
- !ruby/object:RI::MethodSummary 
  name: display_tasks_and_comments
- !ruby/object:RI::MethodSummary 
  name: do_option
- !ruby/object:RI::MethodSummary 
  name: handle_options
- !ruby/object:RI::MethodSummary 
  name: have_rakefile
- !ruby/object:RI::MethodSummary 
  name: help
- !ruby/object:RI::MethodSummary 
  name: init
- !ruby/object:RI::MethodSummary 
  name: invoke_task
- !ruby/object:RI::MethodSummary 
  name: load_imports
- !ruby/object:RI::MethodSummary 
  name: load_rakefile
- !ruby/object:RI::MethodSummary 
  name: options
- !ruby/object:RI::MethodSummary 
  name: parse_task_string
- !ruby/object:RI::MethodSummary 
  name: rake_require
- !ruby/object:RI::MethodSummary 
  name: rakefile_location
- !ruby/object:RI::MethodSummary 
  name: run
- !ruby/object:RI::MethodSummary 
  name: standard_exception_handling
- !ruby/object:RI::MethodSummary 
  name: top_level
- !ruby/object:RI::MethodSummary 
  name: truncate
full_name: Rake::Application
superclass: Object
class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
